"""
Evaluation Module for Manual Ground Truth Verification.

Compares predicted part counts from SAM and OpenCV Watershed against manually labeled
ground-truth counts in ground_truth_counts.csv. Calculates MAE, RMSE, and Accuracy @ +-1 / +-2.
"""

import os
import numpy as np
import pandas as pd
from typing import Dict, Any, Optional


def evaluate_predictions(summary_csv_path: str, ground_truth_csv_path: str) -> Optional[pd.DataFrame]:
    """
    Evaluates predictions against ground truth counts.

    Args:
        summary_csv_path: Path to summary.csv generated by aggregate_results.py.
        ground_truth_csv_path: Path to ground_truth_counts.csv containing 'filename' and 'true_count'.

    Returns:
        pd.DataFrame: Evaluation metrics per method.
    """
    if not os.path.exists(summary_csv_path):
        print(f"[Evaluate ERROR] Summary CSV not found at '{summary_csv_path}'.")
        return None

    if not os.path.exists(ground_truth_csv_path):
        print(f"[Evaluate ERROR] Ground truth CSV not found at '{ground_truth_csv_path}'.")
        return None

    df_pred = pd.read_csv(summary_csv_path)
    df_gt = pd.read_csv(ground_truth_csv_path)

    # Ensure required columns exist
    if "filename" not in df_gt.columns or "true_count" not in df_gt.columns:
        print("[Evaluate ERROR] ground_truth_counts.csv must contain 'filename' and 'true_count' columns.")
        return None

    # Merge predictions with ground truth
    df_merged = pd.merge(df_pred, df_gt[["filename", "true_count"]], on="filename", how="inner")

    if len(df_merged) == 0:
        print("[Evaluate WARNING] No matching filenames found between predictions and ground truth.")
        return None

    print(f"\n========================================================")
    print(f"       EVALUATION METRICS ({len(df_merged)} Ground-Truth Samples)")
    print(f"========================================================")

    metrics = []

    # Evaluate each method column
    for col, method_name in [("sam_count", "SAM Model"), ("cv_count", "OpenCV Watershed")]:
        if col not in df_merged.columns or df_merged[col].isnull().all():
            continue

        valid_mask = df_merged[col].notnull()
        y_true = df_merged.loc[valid_mask, "true_count"].astype(float).values
        y_pred = df_merged.loc[valid_mask, col].astype(float).values

        if len(y_true) == 0:
            continue

        errors = y_pred - y_true
        abs_errors = np.abs(errors)

        mae = np.mean(abs_errors)
        rmse = np.sqrt(np.mean(errors ** 2))
        within_1 = np.mean(abs_errors <= 1) * 100.0
        within_2 = np.mean(abs_errors <= 2) * 100.0
        exact_acc = np.mean(abs_errors == 0) * 100.0

        metrics.append({
            "Method": method_name,
            "Evaluated Samples": len(y_true),
            "MAE": round(mae, 2),
            "RMSE": round(rmse, 2),
            "Exact Match (%)": f"{exact_acc:.1f}%",
            "Within +/-1 (%)": f"{within_1:.1f}%",
            "Within +/-2 (%)": f"{within_2:.1f}%",
        })

    metrics_df = pd.DataFrame(metrics)
    print(metrics_df.to_string(index=False))
    print(f"========================================================\n")

    return metrics_df
